from flask import (
    Flask, request, redirect, url_for, session,
    render_template_string, send_from_directory, flash
)
import sqlite3

# PostgreSQL support for Render
try:
    import psycopg2
    from psycopg2.extras import DictCursor
except ImportError:
    psycopg2 = None
    DictCursor = None
import os
import hashlib
import secrets
import re
from datetime import datetime
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename

app = Flask(__name__)

# =========================================================
# НАСТРОЙКИ
# =========================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_FILE = os.path.join(BASE_DIR, "site.db")
UPLOAD_FOLDER = os.path.join(BASE_DIR, "uploads")
SECRET_FILE = os.path.join(BASE_DIR, "secret_key.txt")

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# Постоянный SECRET KEY — сессии не будут сбрасываться
# после каждого перезапуска программы.
if os.path.exists(SECRET_FILE):
    with open(SECRET_FILE, "r", encoding="utf-8") as f:
        app.secret_key = f.read().strip()
else:
    app.secret_key = secrets.token_hex(32)
    with open(SECRET_FILE, "w", encoding="utf-8") as f:
        f.write(app.secret_key)

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER
app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024

ALLOWED_EXTENSIONS = {"jpg", "jpeg", "png", "gif", "webp"}

# =========================================================
# DATABASE
# =========================================================

class PostgresConnection:
    """Small compatibility wrapper so the existing NEXORA code can use ? placeholders."""
    def __init__(self, dsn):
        if psycopg2 is None:
            raise RuntimeError("psycopg2 is not installed. Add psycopg2-binary to requirements.txt")
        self.raw = psycopg2.connect(dsn, cursor_factory=DictCursor)

    def _adapt(self, sql):
        # SQLite -> PostgreSQL syntax compatibility.
        sql = sql.replace("INSERT OR IGNORE INTO", "INSERT INTO")
        sql = sql.replace("INSERT OR REPLACE INTO comment_reactions", "INSERT INTO comment_reactions")
        sql = sql.replace("username COLLATE NOCASE", "LOWER(username)")
        sql = re.sub(r"INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql, flags=re.I)
        sql = sql.replace("?", "%s")

        # ON CONFLICT behavior used by NEXORA.
        if "INSERT INTO blocks(blocker_id,blocked_id) VALUES(%s,%s)" in sql:
            sql += " ON CONFLICT (blocker_id, blocked_id) DO NOTHING"
        if "INSERT INTO comment_reactions(comment_id,user_id,reaction) VALUES(%s,%s,%s)" in sql:
            sql += " ON CONFLICT (comment_id, user_id) DO UPDATE SET reaction = EXCLUDED.reaction"
        return sql

    def execute(self, sql, params=None):
        # PostgreSQL has no PRAGMA; those checks are handled by column_exists().
        if sql.strip().upper().startswith("PRAGMA "):
            return DummyCursor()
        cur = self.raw.cursor()
        cur.execute(self._adapt(sql), params)
        return cur

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()


class DummyCursor:
    def fetchall(self):
        return []
    def fetchone(self):
        return None


def get_db():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url:
        return PostgresConnection(database_url)
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def column_exists(conn, table, column):
    if isinstance(conn, PostgresConnection):
        row = conn.execute(
            "SELECT column_name AS name FROM information_schema.columns WHERE table_schema='public' AND table_name=? AND column_name=?",
            (table, column)
        ).fetchone()
        return bool(row)
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(row["name"] == column for row in rows)


def init_db():
    conn = get_db()

    # POSTS
    conn.execute("""
        CREATE TABLE IF NOT EXISTS posts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            content TEXT NOT NULL,
            category TEXT DEFAULT 'Без категории',
            image TEXT,
            likes INTEGER DEFAULT 0,
            views INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # USERS
    conn.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    """)

    # COMMENTS
    conn.execute("""
        CREATE TABLE IF NOT EXISTS comments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            post_id INTEGER NOT NULL,
            username TEXT NOT NULL,
            text TEXT NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE
        )
    """)

    # Миграция POSTS
    post_columns = {
        "category": "TEXT DEFAULT 'Без категории'",
        "image": "TEXT",
        "likes": "INTEGER DEFAULT 0",
        "views": "INTEGER DEFAULT 0",
        "created_at": "TEXT"
    }

    for col, definition in post_columns.items():
        if not column_exists(conn, "posts", col):
            conn.execute(f"ALTER TABLE posts ADD COLUMN {col} {definition}")

    # Миграция USERS
    if not column_exists(conn, "users", "role"):
        conn.execute("ALTER TABLE users ADD COLUMN role TEXT DEFAULT 'user'")

    if not column_exists(conn, "users", "created_at"):
        conn.execute("ALTER TABLE users ADD COLUMN created_at TEXT")

    if not column_exists(conn, "users", "avatar"):
        conn.execute("ALTER TABLE users ADD COLUMN avatar TEXT")

    if not column_exists(conn, "posts", "author_id"):
        conn.execute("ALTER TABLE posts ADD COLUMN author_id INTEGER")

    conn.execute("""
        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            text TEXT NOT NULL,
            link TEXT,
            is_read INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        )
    """)

    # Миграция COMMENTS
    if not column_exists(conn, "comments", "user_id"):
        conn.execute("ALTER TABLE comments ADD COLUMN user_id INTEGER")

    # Таблица лайков
    conn.execute("""
        CREATE TABLE IF NOT EXISTS post_likes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            post_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            UNIQUE(post_id, user_id),
            FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        )
    """)

    # Создаём администратора, если его нет.
    admin = conn.execute(
        "SELECT * FROM users WHERE username = ?",
        ("admin",)
    ).fetchone()

    if not admin:
        # Пароль администратора: 1234
        password_hash = generate_password_hash("1234")

        conn.execute("""
            INSERT INTO users
            (username, password, role, created_at)
            VALUES (?, ?, 'admin', ?)
        """, (
            "admin",
            password_hash,
            datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ))
    else:
        # Делаем существующего admin администратором.
        conn.execute(
            "UPDATE users SET role='admin' WHERE username='admin'"
        )

        # Если старый пароль был SHA-256, оставляем совместимость.
        # При следующем входе он автоматически будет заменён
        # на более безопасный хеш Werkzeug.

    # Заполняем created_at у старых пользователей
    conn.execute("""
        UPDATE users
        SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP::text)
        WHERE created_at IS NULL OR created_at = ''
    """)

    # ================= 8.0: СОЦИАЛЬНЫЕ ФУНКЦИИ =================
    conn.execute("""CREATE TABLE IF NOT EXISTS favorites (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER NOT NULL, user_id INTEGER NOT NULL, UNIQUE(post_id,user_id), FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)""")
    conn.execute("""CREATE TABLE IF NOT EXISTS follows (id INTEGER PRIMARY KEY AUTOINCREMENT, follower_id INTEGER NOT NULL, following_id INTEGER NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(follower_id,following_id), CHECK(follower_id != following_id), FOREIGN KEY(follower_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(following_id) REFERENCES users(id) ON DELETE CASCADE)""")
    conn.execute("""CREATE TABLE IF NOT EXISTS ratings (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER NOT NULL, user_id INTEGER NOT NULL, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5), created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(post_id,user_id), FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)""")
    conn.execute("""CREATE TABLE IF NOT EXISTS activity (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL, link TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""")
    if not column_exists(conn, "comments", "parent_id"):
        conn.execute("ALTER TABLE comments ADD COLUMN parent_id INTEGER")
    # ================= 9.0: ПРОФИЛИ, ДОСТИЖЕНИЯ И ЛЕНТА =================
    conn.execute("""CREATE TABLE IF NOT EXISTS achievements (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, code TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id,code), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)""")
    conn.execute("""CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, sender_id INTEGER NOT NULL, receiver_id INTEGER NOT NULL, text TEXT NOT NULL, is_read INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(receiver_id) REFERENCES users(id) ON DELETE CASCADE)""")
    conn.execute("""CREATE TABLE IF NOT EXISTS blocks (id INTEGER PRIMARY KEY AUTOINCREMENT, blocker_id INTEGER NOT NULL, blocked_id INTEGER NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(blocker_id,blocked_id), CHECK(blocker_id != blocked_id), FOREIGN KEY(blocker_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(blocked_id) REFERENCES users(id) ON DELETE CASCADE)""")
    conn.execute("""CREATE TABLE IF NOT EXISTS comment_reactions (id INTEGER PRIMARY KEY AUTOINCREMENT, comment_id INTEGER NOT NULL, user_id INTEGER NOT NULL, reaction TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(comment_id,user_id), FOREIGN KEY(comment_id) REFERENCES comments(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)""")
    conn.execute("""CREATE INDEX IF NOT EXISTS idx_messages_receiver ON messages(receiver_id, is_read, created_at)""")
    conn.execute("""CREATE INDEX IF NOT EXISTS idx_messages_pair ON messages(sender_id, receiver_id, created_at)""")
    conn.execute("""CREATE INDEX IF NOT EXISTS idx_reactions_comment ON comment_reactions(comment_id)""")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_comments_post_parent ON comments(post_id,parent_id,id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_follows_following ON follows(following_id,follower_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id)")

    # Старые комментарии могут не иметь user_id — это нормально.
    conn.commit()
    conn.close()


init_db()

# NEXORA 10.0 migration — works on both SQLite and PostgreSQL
conn = get_db()
try:
    if not column_exists(conn, "users", "last_seen"):
        conn.execute("ALTER TABLE users ADD COLUMN last_seen TEXT")
    conn.commit()
except Exception:
    conn.rollback()
finally:
    conn.close()

# =========================================================
# HELPERS
# =========================================================

def allowed_file(filename):
    return (
        "." in filename and
        filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS
    )


def current_user():
    user_id = session.get("user_id")

    if not user_id:
        return None

    conn = get_db()
    user = conn.execute(
        "SELECT * FROM users WHERE id = ?",
        (user_id,)
    ).fetchone()
    conn.close()

    return user


def add_notification(user_id, text, link=None):
    conn = get_db()
    conn.execute("""
        INSERT INTO notifications (user_id, text, link, is_read, created_at)
        VALUES (?, ?, ?, 0, ?)
    """, (user_id, text, link, datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
    conn.commit()
    conn.close()


def unread_notifications_count(user_id):
    conn = get_db()
    count = conn.execute(
        "SELECT COUNT(*) FROM notifications WHERE user_id = ? AND is_read = 0",
        (user_id,)
    ).fetchone()[0]
    conn.close()
    return count


@app.context_processor
def inject_ui_data():
    user = current_user()
    if user:
        conn = get_db()
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        try:
            conn.execute("UPDATE users SET last_seen=? WHERE id=?", (now, user["id"]))
            conn.commit()
        except Exception:
            pass
        conn.close()
    return {"unread_count": unread_notifications_count(user["id"]) if user else 0,
            "unread_messages": unread_messages_count(user["id"]) if user else 0}


def unread_messages_count(user_id):
    conn = get_db()
    count = conn.execute("SELECT COUNT(*) FROM messages WHERE receiver_id = ? AND is_read = 0", (user_id,)).fetchone()[0]
    conn.close()
    return count


def is_blocked(a, b):
    conn = get_db()
    row = conn.execute("SELECT 1 FROM blocks WHERE blocker_id=? AND blocked_id=?", (a,b)).fetchone()
    conn.close()
    return bool(row)

def login_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if not session.get("user_id"):
            flash("Сначала войдите в аккаунт.")
            return redirect(url_for("login"))
        return func(*args, **kwargs)
    return wrapper


def admin_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        user = current_user()

        if not user or user["role"] != "admin":
            flash("Доступ только для администратора.")
            return redirect(url_for("index"))

        return func(*args, **kwargs)
    return wrapper


# =========================================================
# NEXORA 9.0 — СОЦИАЛЬНЫЕ ФУНКЦИИ
# =========================================================

@app.route("/favorite/<int:post_id>", methods=["POST"])
@login_required
def toggle_favorite(post_id):
    user=current_user(); conn=get_db()
    post=conn.execute("SELECT id,title FROM posts WHERE id=?",(post_id,)).fetchone()
    if not post:
        conn.close(); flash("Пост не найден."); return redirect(url_for("index"))
    row=conn.execute("SELECT id FROM favorites WHERE post_id=? AND user_id=?",(post_id,user["id"])).fetchone()
    if row:
        conn.execute("DELETE FROM favorites WHERE id=?",(row["id"],)); msg="Удалено из избранного ⭐"
    else:
        conn.execute("INSERT INTO favorites(post_id,user_id) VALUES(?,?)",(post_id,user["id"])); msg="Добавлено в избранное ⭐"
    conn.commit(); conn.close(); flash(msg); return redirect(url_for("view_post",post_id=post_id))

@app.route("/favorites")
@login_required
def favorites_page():
    user=current_user(); conn=get_db()
    posts=conn.execute("SELECT posts.*, (SELECT AVG(rating) FROM ratings WHERE ratings.post_id=posts.id) avg_rating FROM posts JOIN favorites ON favorites.post_id=posts.id WHERE favorites.user_id=? ORDER BY favorites.id DESC",(user["id"],)).fetchall(); conn.close()
    body="""<div class='hero'><span class='badge'>NEXORA 9.0</span><h1>⭐ Избранное</h1><p>Твои сохранённые посты.</p></div>
    {% if posts %}{% for post in posts %}<div class='card post'><h2>{{ post['title'] }}</h2><div class='meta'>📁 {{ post['category'] }} · 👁 {{ post['views'] }} · ❤️ {{ post['likes'] }} · ⭐ {{ '%.1f'|format(post['avg_rating'] or 0) }}</div><p>{{ post['content'][:220] }}{% if post['content']|length>220 %}...{% endif %}</p><a class='btn' href='{{ url_for('view_post',post_id=post['id']) }}'>Открыть →</a></div>{% endfor %}{% else %}<div class='card'><h3>Пока пусто ⭐</h3><p>Открой пост и добавь его в избранное.</p></div>{% endif %}"""
    return render_template_string(BASE_HTML,title="Избранное",body=render_template_string(body,posts=posts),user=user)

@app.route("/popular")
def popular_page():
    conn=get_db(); posts=conn.execute("SELECT posts.*, AVG(ratings.rating) avg_rating, COUNT(DISTINCT favorites.id) favs FROM posts LEFT JOIN ratings ON ratings.post_id=posts.id LEFT JOIN favorites ON favorites.post_id=posts.id GROUP BY posts.id ORDER BY (posts.likes*3+posts.views+COUNT(DISTINCT favorites.id)*4+COALESCE(AVG(ratings.rating),0)*5) DESC, posts.id DESC LIMIT 30").fetchall(); conn.close()
    body="""<div class='hero'><span class='badge'>🔥 TOP</span><h1>🔥 Популярное</h1><p>Посты с лучшей активностью.</p></div>{% for post in posts %}<div class='card post'><h2>{{ post['title'] }}</h2><div class='meta'>❤️ {{ post['likes'] }} · 👁 {{ post['views'] }} · ⭐ {{ '%.1f'|format(post['avg_rating'] or 0) }} · 🔖 {{ post['favs'] }}</div><p>{{ post['content'][:220] }}{% if post['content']|length>220 %}...{% endif %}</p><a class='btn' href='{{ url_for('view_post',post_id=post['id']) }}'>Читать →</a></div>{% else %}<div class='card'>Постов пока нет.</div>{% endfor %}"""
    return render_template_string(BASE_HTML,title="Популярное",body=render_template_string(body,posts=posts),user=current_user())

@app.route("/rate/<int:post_id>", methods=["POST"])
@login_required
def rate_post(post_id):
    try: rating=max(1,min(5,int(request.form.get("rating","5"))))
    except (ValueError,TypeError): rating=5
    user=current_user(); conn=get_db(); post=conn.execute("SELECT id FROM posts WHERE id=?",(post_id,)).fetchone()
    if not post:
        conn.close(); flash("Пост не найден."); return redirect(url_for("index"))
    now=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    old=conn.execute("SELECT id FROM ratings WHERE post_id=? AND user_id=?",(post_id,user["id"])).fetchone()
    if old: conn.execute("UPDATE ratings SET rating=?,created_at=? WHERE id=?",(rating,now,old["id"]))
    else: conn.execute("INSERT INTO ratings(post_id,user_id,rating,created_at) VALUES(?,?,?,?)",(post_id,user["id"],rating,now))
    conn.commit(); conn.close(); flash("Оценка сохранена ⭐"); return redirect(url_for("view_post",post_id=post_id))

@app.route("/follow/<int:user_id>", methods=["POST"])
@login_required
def toggle_follow(user_id):
    me=current_user()
    if me["id"]==user_id: flash("Нельзя подписаться на себя."); return redirect(url_for("public_profile",user_id=user_id))
    conn=get_db(); target=conn.execute("SELECT id,username FROM users WHERE id=?",(user_id,)).fetchone()
    if not target:
        conn.close(); flash("Пользователь не найден."); return redirect(url_for("index"))
    row=conn.execute("SELECT id FROM follows WHERE follower_id=? AND following_id=?",(me["id"],user_id)).fetchone()
    if row:
        conn.execute("DELETE FROM follows WHERE id=?",(row["id"],)); msg="Подписка отменена."
    else:
        conn.execute("INSERT INTO follows(follower_id,following_id,created_at) VALUES(?,?,?)",(me["id"],user_id,datetime.now().strftime("%Y-%m-%d %H:%M:%S"))); msg="Вы подписались! 👥"
        conn.commit(); conn.close(); add_notification(user_id,f"👥 {me['username']} подписался на вас",url_for("public_profile",user_id=me["id"])); flash(msg); return redirect(url_for("public_profile",user_id=user_id))
    conn.commit(); conn.close(); flash(msg); return redirect(url_for("public_profile",user_id=user_id))

@app.route("/user/<int:user_id>")
def public_profile(user_id):
    conn=get_db(); u=conn.execute("SELECT * FROM users WHERE id=?",(user_id,)).fetchone()
    if not u:
        conn.close(); return page("Ошибка","<div class='card'><h2>Пользователь не найден.</h2></div>")
    stats=conn.execute("SELECT COUNT(*) c FROM posts WHERE author_id=?",(user_id,)).fetchone()["c"]
    followers=conn.execute("SELECT COUNT(*) c FROM follows WHERE following_id=?",(user_id,)).fetchone()["c"]
    following=conn.execute("SELECT COUNT(*) c FROM follows WHERE follower_id=?",(user_id,)).fetchone()["c"]
    posts=conn.execute("SELECT * FROM posts WHERE author_id=? ORDER BY id DESC LIMIT 10",(user_id,)).fetchall()
    me=current_user(); following_me=False
    if me: following_me=bool(conn.execute("SELECT 1 FROM follows WHERE follower_id=? AND following_id=?",(me["id"],user_id)).fetchone())
    conn.close()
    body="""<div class='hero'><div class='profile-avatar'>{% if u['avatar'] %}<img src='{{ url_for('uploaded_file',filename=u['avatar']) }}'>{% else %}👤{% endif %}</div><span class='badge'>ПРОФИЛЬ</span><h1>{{ u['username'] }}</h1><div class='stat'>📝 <strong>{{ stats }}</strong> постов</div><div class='stat'>👥 <strong>{{ followers }}</strong> подписчиков</div><div class='stat'>➡️ <strong>{{ following }}</strong> подписок</div>{% if me and me['id']!=u['id'] %}<form method='post' action='{{ url_for('toggle_follow',user_id=u['id']) }}' class='actions'><button>{% if following_me %}✓ Вы подписаны{% else %}➕ Подписаться{% endif %}</button></form>{% endif %}</div>{% for post in posts %}<div class='card'><h2>{{ post['title'] }}</h2><div class='meta'>👁 {{ post['views'] }} · ❤️ {{ post['likes'] }}</div><a class='btn' href='{{ url_for('view_post',post_id=post['id']) }}'>Читать →</a></div>{% else %}<div class='card'><p>Постов пока нет.</p></div>{% endfor %}"""
    return render_template_string(BASE_HTML,title=u["username"],body=render_template_string(body,u=u,stats=stats,followers=followers,following=following,posts=posts,me=me,following_me=following_me),user=me)

@app.route("/activity")
def activity_page():
    conn=get_db(); rows=conn.execute("SELECT * FROM activity ORDER BY id DESC LIMIT 50").fetchall(); conn.close()
    body="""<div class='hero'><span class='badge'>⚡ LIVE</span><h1>⚡ Активность</h1><p>Последние события на сайте.</p></div>{% for a in rows %}<div class='card'><div class='meta'>{{ a['created_at'] }}</div>{% if a['link'] %}<a href='{{ a['link'] }}'>{{ a['text'] }}</a>{% else %}{{ a['text'] }}{% endif %}</div>{% else %}<div class='card'>Активность пока пустая.</div>{% endfor %}"""
    return render_template_string(BASE_HTML,title="Активность",body=render_template_string(body,rows=rows),user=current_user())

@app.route("/stats")
@login_required
def stats_page():
    u=current_user(); conn=get_db(); posts=conn.execute("SELECT COUNT(*) c, COALESCE(SUM(views),0) views, COALESCE(SUM(likes),0) likes FROM posts WHERE author_id=?",(u["id"],)).fetchone(); comments=conn.execute("SELECT COUNT(*) c FROM comments WHERE user_id=?",(u["id"],)).fetchone()["c"]; favs=conn.execute("SELECT COUNT(*) c FROM favorites WHERE user_id=?",(u["id"],)).fetchone()["c"]; followers=conn.execute("SELECT COUNT(*) c FROM follows WHERE following_id=?",(u["id"],)).fetchone()["c"]; conn.close()
    body="""<div class='hero'><span class='badge'>📊 STATS</span><h1>📊 Моя статистика</h1><div class='stat'>📝 <strong>{{ p['c'] }}</strong> постов</div><div class='stat'>👁 <strong>{{ p['views'] }}</strong> просмотров</div><div class='stat'>❤️ <strong>{{ p['likes'] }}</strong> лайков</div><div class='stat'>💬 <strong>{{ comments }}</strong> комментариев</div><div class='stat'>⭐ <strong>{{ favs }}</strong> избранных</div><div class='stat'>👥 <strong>{{ followers }}</strong> подписчиков</div></div>"""
    return render_template_string(BASE_HTML,title="Статистика",body=render_template_string(body,p=posts,comments=comments,favs=favs,followers=followers),user=u)

# =========================================================
# NEXORA 9.0 — НОВЫЕ ФУНКЦИИ
# =========================================================

ACHIEVEMENTS = [
    ("first_post", "📝 Первый пост", "Опубликовал свой первый пост."),
    ("ten_posts", "🔥 10 постов", "Опубликовал 10 постов."),
    ("first_comment", "💬 Первый комментарий", "Оставил первый комментарий."),
    ("ten_comments", "💬 Активный комментатор", "Оставил 10 комментариев."),
    ("first_follow", "👥 Первый подписчик", "Подписался на первого автора."),
    ("ten_followers", "👑 10 подписчиков", "Получил 10 подписчиков."),
    ("first_favorite", "⭐ Первое избранное", "Добавил первый пост в избранное."),
    ("five_ratings", "🌟 Критик", "Оценил 5 постов."),
]

def check_achievements(user_id):
    conn = get_db()
    stats = {
        "posts": conn.execute("SELECT COUNT(*) c FROM posts WHERE author_id=?", (user_id,)).fetchone()["c"],
        "comments": conn.execute("SELECT COUNT(*) c FROM comments WHERE user_id=?", (user_id,)).fetchone()["c"],
        "following": conn.execute("SELECT COUNT(*) c FROM follows WHERE follower_id=?", (user_id,)).fetchone()["c"],
        "followers": conn.execute("SELECT COUNT(*) c FROM follows WHERE following_id=?", (user_id,)).fetchone()["c"],
        "favorites": conn.execute("SELECT COUNT(*) c FROM favorites WHERE user_id=?", (user_id,)).fetchone()["c"],
        "ratings": conn.execute("SELECT COUNT(*) c FROM ratings WHERE user_id=?", (user_id,)).fetchone()["c"],
    }
    rules = {
        "first_post": stats["posts"] >= 1,
        "ten_posts": stats["posts"] >= 10,
        "first_comment": stats["comments"] >= 1,
        "ten_comments": stats["comments"] >= 10,
        "first_follow": stats["following"] >= 1,
        "ten_followers": stats["followers"] >= 10,
        "first_favorite": stats["favorites"] >= 1,
        "five_ratings": stats["ratings"] >= 5,
    }
    new_items=[]
    for code,title,desc in ACHIEVEMENTS:
        if rules.get(code):
            exists=conn.execute("SELECT id FROM achievements WHERE user_id=? AND code=?",(user_id,code)).fetchone()
            if not exists:
                conn.execute("INSERT INTO achievements(user_id,code,title,description) VALUES(?,?,?,?)",(user_id,code,title,desc))
                new_items.append(title)
    conn.commit(); conn.close()
    return new_items

@app.after_request
def security_headers(response):
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    return response

@app.route("/reply/<int:comment_id>", methods=["POST"])
@login_required
def reply_comment(comment_id):
    user=current_user(); text=request.form.get("text","").strip()
    if not text or len(text)>1000:
        flash("Ответ пустой или слишком длинный.")
        return redirect(request.referrer or url_for("index"))
    conn=get_db()
    parent=conn.execute("SELECT id,post_id,user_id,username FROM comments WHERE id=?",(comment_id,)).fetchone()
    if not parent:
        conn.close(); flash("Комментарий не найден."); return redirect(url_for("index"))
    conn.execute("INSERT INTO comments(post_id,username,text,created_at,user_id,parent_id) VALUES(?,?,?,?,?,?)",(parent["post_id"],user["username"],text,datetime.now().strftime("%Y-%m-%d %H:%M:%S"),user["id"],parent["id"]))
    conn.commit(); conn.close()
    if parent["user_id"] and parent["user_id"] != user["id"]:
        add_notification(parent["user_id"],f"💬 {user['username']} ответил на твой комментарий.",url_for("view_post",post_id=parent["post_id"]))
    check_achievements(user["id"])
    flash("Ответ добавлен 💬")
    return redirect(url_for("view_post",post_id=parent["post_id"]))

@app.route("/achievements")
@login_required
def achievements_page():
    u=current_user(); check_achievements(u["id"])
    conn=get_db(); rows=conn.execute("SELECT * FROM achievements WHERE user_id=? ORDER BY id DESC",(u["id"],)).fetchall(); conn.close()
    body="""<div class='hero'><span class='badge'>🏆 NEXORA 9.0</span><h1>🏆 Мои достижения</h1><p>Продолжай пользоваться NEXORA и открывай новые награды.</p></div><div class='grid'>{% for a in rows %}<div class='card'><h2>{{ a['title'] }}</h2><p>{{ a['description'] }}</p><div class='meta'>Получено: {{ a['created_at'] }}</div></div>{% else %}<div class='card'><h3>Пока нет достижений</h3><p>Напиши комментарий, оцени пост или создай публикацию.</p></div>{% endfor %}</div>"""
    return render_template_string(BASE_HTML,title="Достижения",body=render_template_string(body,rows=rows),user=u)

@app.route("/top-authors")
def top_authors_page():
    conn=get_db()
    rows=conn.execute("""SELECT u.id,u.username,u.avatar,COUNT(DISTINCT p.id) posts,COUNT(DISTINCT f.follower_id) followers,COALESCE(SUM(p.views),0) views,COALESCE(SUM(p.likes),0) likes FROM users u LEFT JOIN posts p ON p.author_id=u.id LEFT JOIN follows f ON f.following_id=u.id GROUP BY u.id ORDER BY (followers*5+likes*3+views+posts*10) DESC, u.id DESC LIMIT 30""").fetchall(); conn.close()
    body="""<div class='hero'><span class='badge'>👑 TOP AUTHORS</span><h1>👑 Лучшие авторы</h1><p>Авторы с самой высокой активностью.</p></div>{% for u in rows %}<div class='card'><div class='profile-line'>{% if u['avatar'] %}<img class='mini-avatar' src='{{ url_for('uploaded_file',filename=u['avatar']) }}'>{% else %}<div class='mini-avatar'>👤</div>{% endif %}<div><h2 style='margin:0'>{{ u['username'] }}</h2><div class='meta'>📝 {{ u['posts'] }} · 👥 {{ u['followers'] }} · 👁 {{ u['views'] }} · ❤️ {{ u['likes'] }}</div></div></div><a class='btn' href='{{ url_for('public_profile',user_id=u['id']) }}'>Профиль →</a></div>{% else %}<div class='card'>Пока нет авторов.</div>{% endfor %}"""
    return render_template_string(BASE_HTML,title="Лучшие авторы",body=render_template_string(body,rows=rows),user=current_user())

@app.route("/for-you")
@login_required
def for_you_page():
    u=current_user(); conn=get_db()
    posts=conn.execute("""SELECT p.*,u.username author,COALESCE((SELECT AVG(r.rating) FROM ratings r WHERE r.post_id=p.id),0) avg_rating FROM posts p LEFT JOIN users u ON u.id=p.author_id WHERE p.author_id IN (SELECT following_id FROM follows WHERE follower_id=?) AND p.author_id != ? ORDER BY p.id DESC LIMIT 50""",(u["id"],u["id"])).fetchall()
    conn.close()
    body="""<div class='hero'><span class='badge'>🔥 FOR YOU</span><h1>🔥 Для тебя</h1><p>Новые публикации авторов, на которых ты подписан.</p></div>{% for p in posts %}<div class='card post'><h2>{{ p['title'] }}</h2><div class='meta'>👤 {{ p['author'] or 'Автор' }} · 👁 {{ p['views'] }} · ❤️ {{ p['likes'] }} · ⭐ {{ '%.1f'|format(p['avg_rating']) }}</div><p>{{ p['content'][:260] }}{% if p['content']|length>260 %}...{% endif %}</p><a class='btn' href='{{ url_for('view_post',post_id=p['id']) }}'>Читать →</a></div>{% else %}<div class='card'><h3>Лента пока пустая</h3><p>Подпишись на авторов — и их новые посты появятся здесь.</p><a class='btn' href='{{ url_for('top_authors_page') }}'>Найти авторов →</a></div>{% endfor %}"""
    return render_template_string(BASE_HTML,title="Для тебя",body=render_template_string(body,posts=posts),user=u)

# =========================================================
# HTML
# =========================================================

# =========================================================
# NEXORA 10.0 — СООБЩЕНИЯ, БЛОКИРОВКА, РЕАКЦИИ
# =========================================================

@app.route("/messages")
@login_required
def messages_page():
    user = current_user(); conn = get_db()
    rows = conn.execute("""
        SELECT u.id, u.username, u.avatar, u.last_seen,
               (SELECT text FROM messages m2 WHERE ((m2.sender_id=? AND m2.receiver_id=u.id) OR (m2.sender_id=u.id AND m2.receiver_id=?)) ORDER BY m2.id DESC LIMIT 1) AS last_text,
               (SELECT created_at FROM messages m3 WHERE ((m3.sender_id=? AND m3.receiver_id=u.id) OR (m3.sender_id=u.id AND m3.receiver_id=?)) ORDER BY m3.id DESC LIMIT 1) AS last_time,
               (SELECT COUNT(*) FROM messages m4 WHERE m4.sender_id=u.id AND m4.receiver_id=? AND m4.is_read=0) AS unread
        FROM users u WHERE u.id != ? ORDER BY last_time DESC, u.username COLLATE NOCASE
    """, (user['id'],user['id'],user['id'],user['id'],user['id'],user['id'])).fetchall(); conn.close()
    body = """
    <div class="hero"><h1>💬 Сообщения</h1><p>Общайся с пользователями NEXORA.</p></div>
    <div class="card"><form class="search" action="{{ url_for('user_search') }}"><input name="q" placeholder="🔎 Найти пользователя..." required><button>Найти</button></form></div>
    {% for u in rows %}<div class="card profile-line">
      {% if u['avatar'] %}<img class="mini-avatar" src="{{ url_for('uploaded_file',filename=u['avatar']) }}">{% else %}<div class="mini-avatar">{{ u['username'][0].upper() }}</div>{% endif %}
      <div style="flex:1"><a href="{{ url_for('conversation', user_id=u['id']) }}"><b>{{ u['username'] }}</b></a><div class="meta">{% if u['last_text'] %}{{ u['last_text'][:70] }}{% else %}Начать разговор{% endif %}{% if u['unread'] %} · 🔔 {{ u['unread'] }}{% endif %}</div></div>
      <a class="btn btn-gray" href="{{ url_for('conversation', user_id=u['id']) }}">Открыть</a>
    </div>{% else %}<div class="card">Пока нет других пользователей.</div>{% endfor %}
    """
    return render_template_string(BASE_HTML,title='Сообщения',body=render_template_string(body,rows=rows),user=user)

@app.route('/messages/<int:user_id>', methods=['GET','POST'])
@login_required
def conversation(user_id):
    me=current_user(); conn=get_db(); other=conn.execute('SELECT * FROM users WHERE id=?',(user_id,)).fetchone()
    if not other or other['id']==me['id']:
        conn.close(); flash('Пользователь не найден.'); return redirect(url_for('messages_page'))
    blocked = conn.execute('SELECT 1 FROM blocks WHERE blocker_id=? AND blocked_id=?',(me['id'],user_id)).fetchone() or conn.execute('SELECT 1 FROM blocks WHERE blocker_id=? AND blocked_id=?',(user_id,me['id'])).fetchone()
    if request.method=='POST':
        text=request.form.get('text','').strip()
        if blocked: flash('Нельзя отправлять сообщения этому пользователю.')
        elif text:
            text=text[:2000]
            conn.execute('INSERT INTO messages(sender_id,receiver_id,text,is_read,created_at) VALUES(?,?,?,?,?)',(me['id'],user_id,text,0,datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
            conn.commit(); conn.close(); add_notification(user_id,f'💬 Новое сообщение от {me["username"]}',url_for('conversation',user_id=me['id'])); return redirect(url_for('conversation',user_id=user_id))
    conn.execute('UPDATE messages SET is_read=1 WHERE sender_id=? AND receiver_id=?',(user_id,me['id'])); conn.commit()
    msgs=conn.execute('SELECT * FROM messages WHERE (sender_id=? AND receiver_id=?) OR (sender_id=? AND receiver_id=?) ORDER BY id ASC',(me['id'],user_id,user_id,me['id'])).fetchall(); conn.close()
    body = """
    <div class="card"><div class="profile-line"><div class="mini-avatar">{{ other['username'][0].upper() }}</div><div><h2 style="margin:0">💬 {{ other['username'] }}</h2><div class="meta">{% if other['last_seen'] %}Последний визит: {{ other['last_seen'] }}{% endif %}</div></div></div>
    {% if blocked %}<div class="flash">🚫 Общение заблокировано.</div>{% endif %}
    <div style="max-height:55vh;overflow:auto;padding:5px">{% for m in msgs %}<div style="text-align:{{ 'right' if m['sender_id']==me['id'] else 'left' }};margin:10px 0"><span class="badge">{{ 'Ты' if m['sender_id']==me['id'] else other['username'] }}</span><div class="card" style="display:inline-block;max-width:85%;margin:5px 0;padding:11px">{{ m['text'] }}<div class="comment-date">{{ m['created_at'] }}</div></div></div>{% else %}<p>Начни разговор 👋</p>{% endfor %}</div>
    {% if not blocked %}<form method="post"><textarea name="text" maxlength="2000" placeholder="Напиши сообщение..." required></textarea><button>📨 Отправить</button></form>{% endif %}
    </div>
    """
    return render_template_string(BASE_HTML,title='Диалог',body=render_template_string(body,other=other,me=me,msgs=msgs,blocked=bool(blocked)),user=me)

@app.route('/users/search')
@login_required
def user_search():
    q=request.args.get('q','').strip()[:50]; me=current_user(); conn=get_db()
    users=conn.execute('SELECT id,username,avatar,last_seen FROM users WHERE id!=? AND username LIKE ? ORDER BY username LIMIT 30',(me['id'],'%'+q+'%')).fetchall(); conn.close()
    body = """
    <div class="hero"><h1>🔎 Пользователи</h1><form class="search"><input name="q" value="{{ q }}" placeholder="Имя"><button>Найти</button></form></div>
    {% for u in users %}<div class="card profile-line">{% if u['avatar'] %}<img class="mini-avatar" src="{{ url_for('uploaded_file',filename=u['avatar']) }}">{% else %}<div class="mini-avatar">{{ u['username'][0].upper() }}</div>{% endif %}<div style="flex:1"><a href="{{ url_for('public_user',user_id=u['id']) }}"><b>{{ u['username'] }}</b></a><div class="meta">{% if u['last_seen'] %}Последний визит: {{ u['last_seen'] }}{% endif %}</div></div><a class="btn" href="{{ url_for('conversation',user_id=u['id']) }}">💬 Написать</a></div>{% else %}<div class="card">Ничего не найдено.</div>{% endfor %}
    """
    return render_template_string(BASE_HTML,title='Поиск пользователей',body=render_template_string(body,users=users,q=q),user=me)

@app.route('/block/<int:user_id>', methods=['POST'])
@login_required
def block_user(user_id):
    me=current_user()
    if user_id==me['id']: return redirect(url_for('profile'))
    conn=get_db(); exists=conn.execute('SELECT 1 FROM users WHERE id=?',(user_id,)).fetchone()
    if exists:
        row=conn.execute('SELECT 1 FROM blocks WHERE blocker_id=? AND blocked_id=?',(me['id'],user_id)).fetchone()
        if row: conn.execute('DELETE FROM blocks WHERE blocker_id=? AND blocked_id=?',(me['id'],user_id)); flash('Пользователь разблокирован.')
        else: conn.execute('INSERT OR IGNORE INTO blocks(blocker_id,blocked_id) VALUES(?,?)',(me['id'],user_id)); flash('Пользователь заблокирован.')
        conn.commit()
    conn.close(); return redirect(request.referrer or url_for('profile'))

@app.route('/react/<int:comment_id>/<reaction>', methods=['POST'])
@login_required
def react_comment(comment_id,reaction):
    if reaction not in ('like','love','fire'): return redirect(request.referrer or url_for('index'))
    me=current_user(); conn=get_db(); exists=conn.execute('SELECT 1 FROM comments WHERE id=?',(comment_id,)).fetchone()
    if exists:
        old=conn.execute('SELECT reaction FROM comment_reactions WHERE comment_id=? AND user_id=?',(comment_id,me['id'])).fetchone()
        if old and old['reaction']==reaction: conn.execute('DELETE FROM comment_reactions WHERE comment_id=? AND user_id=?',(comment_id,me['id']))
        else: conn.execute('INSERT OR REPLACE INTO comment_reactions(comment_id,user_id,reaction) VALUES(?,?,?)',(comment_id,me['id'],reaction))
        conn.commit()
    conn.close(); return redirect(request.referrer or url_for('index'))


BASE_HTML = """
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="theme-color" content="#07110a">
<title>{{ title }} — NEXORA</title>
<style>
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;background:#050805;color:#eefaf0;font-family:Arial,Helvetica,sans-serif;min-height:100vh}
body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 50% -10%,rgba(0,255,100,.10),transparent 38%);z-index:-1}
a{color:#39ff78}
header{position:sticky;top:0;z-index:50;background:rgba(5,8,5,.90);backdrop-filter:blur(14px);border-bottom:1px solid #123d20;box-shadow:0 4px 25px rgba(0,0,0,.35)}
.nav{max-width:1100px;margin:auto;padding:12px 16px;display:flex;justify-content:space-between;align-items:center;gap:12px}
.logo{color:#39ff78;text-decoration:none;font-size:23px;font-weight:900;letter-spacing:.3px;text-shadow:0 0 14px rgba(57,255,120,.35)}
.navlinks{display:flex;gap:6px;align-items:center;flex-wrap:wrap;justify-content:flex-end}
.navlinks a{color:#d8eadc;text-decoration:none;padding:9px 11px;border-radius:10px;transition:.2s}
.navlinks a:hover{color:#39ff78;background:#0d1c11;box-shadow:0 0 14px rgba(57,255,120,.08)}
.navlinks b{background:#39ff78;color:#031008;padding:2px 7px;border-radius:99px;font-size:11px}
.container{max-width:1100px;margin:auto;padding:28px 16px 70px}
h1{font-size:34px;margin:0 0 20px}h2{margin-top:0}h3{margin-top:0}
.card{background:linear-gradient(145deg,#0b120d,#080d09);border:1px solid #163a21;border-radius:18px;padding:20px;margin-bottom:18px;box-shadow:0 10px 35px rgba(0,0,0,.25);transition:.2s}
.card:hover{border-color:#24683a;box-shadow:0 12px 40px rgba(0,0,0,.32)}
.post{overflow:hidden}.post:hover{transform:translateY(-3px);border-color:#2bd865}
.post img{width:100%;max-height:430px;object-fit:cover;border-radius:14px;margin-bottom:14px;border:1px solid #173b21}
.meta{color:#82a08a;font-size:13px;margin:9px 0 14px}.content{white-space:pre-wrap;line-height:1.75;color:#dce9df}
input,textarea,select{width:100%;padding:13px 14px;margin:7px 0 14px;border-radius:11px;border:1px solid #1b4927;background:#050a06;color:#effff2;outline:none;font-size:15px;transition:.2s}
input:focus,textarea:focus,select:focus{border-color:#39ff78;box-shadow:0 0 0 3px rgba(57,255,120,.10)}
textarea{min-height:150px;resize:vertical}
button,.btn{display:inline-block;border:1px solid #2be36a;background:linear-gradient(135deg,#19c957,#39ff78);color:#031008;padding:11px 16px;border-radius:11px;cursor:pointer;text-decoration:none;font-size:14px;font-weight:800;transition:.2s;box-shadow:0 4px 18px rgba(57,255,120,.12)}
button:hover,.btn:hover{transform:translateY(-1px);filter:brightness(1.08);box-shadow:0 6px 22px rgba(57,255,120,.20)}
.btn-danger{background:#a91f32;border-color:#e83d54;color:#fff;box-shadow:none}.btn-danger:hover{box-shadow:0 5px 18px rgba(232,61,84,.2)}
.btn-green{background:#19c957;color:#031008}.btn-gray{background:#101a13;border-color:#285335;color:#d8eadc;box-shadow:none}
.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px;align-items:center}
.search{display:flex;gap:9px}.search input{margin:0}.search button{white-space:nowrap}
.flash{background:#0d2413;border:1px solid #24683a;color:#bfffd0;padding:13px 15px;border-radius:12px;margin-bottom:16px}
.comment{border-top:1px solid #17351f;padding:15px 0}.comment:first-child{border-top:none}.comment-user{font-weight:800;color:#50ff89}.comment-date{color:#64806b;font-size:12px}
.profile-avatar{width:88px;height:88px;background:linear-gradient(135deg,#0f5d2b,#39ff78);border-radius:50%;display:flex;justify-content:center;align-items:center;font-size:34px;margin-bottom:15px;border:2px solid #39ff78;box-shadow:0 0 25px rgba(57,255,120,.16);overflow:hidden}.profile-avatar img{width:100%;height:100%;object-fit:cover}
.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.profile-line{display:flex;gap:13px;align-items:center;margin-bottom:14px}.mini-avatar{width:54px;height:54px;border-radius:50%;object-fit:cover;background:#0f5d2b;border:1px solid #39ff78;display:flex;align-items:center;justify-content:center}.stat{display:inline-block;background:#0b170e;border:1px solid #194b29;padding:13px 15px;border-radius:12px;margin:4px;color:#bcebc8}.stat strong{color:#39ff78}
.hero{padding:25px;border-radius:20px;margin-bottom:18px;background:linear-gradient(135deg,#0a1d0f,#071009);border:1px solid #1c5b30;box-shadow:0 0 45px rgba(57,255,120,.06)}
.badge{display:inline-block;padding:5px 9px;border-radius:99px;background:#0e2916;border:1px solid #245f34;color:#58ff8c;font-size:12px;font-weight:700}
@media(max-width:700px){ .grid{grid-template-columns:1fr}
 .container{padding:20px 12px 82px}.nav{padding:10px 12px}.logo{font-size:20px}.navlinks{gap:3px}.navlinks a{font-size:12px;padding:8px 7px}.navlinks a:nth-child(1),.navlinks a:nth-last-child(1){display:none}h1{font-size:28px}.card{padding:16px;border-radius:15px}.search{flex-direction:column}.search button{width:100%}
}
@media(max-width:480px){
 header{position:fixed;left:0;right:0;bottom:0;top:auto;border-top:1px solid #123d20;border-bottom:0;background:rgba(5,8,5,.96)}
 .nav{justify-content:center;padding:7px}.logo{display:none}.navlinks{width:100%;justify-content:space-around;flex-wrap:nowrap}.navlinks a{font-size:11px;text-align:center;padding:8px 5px;min-width:48px}.navlinks a:nth-child(1),.navlinks a:nth-last-child(1){display:block}.container{padding-bottom:82px}
}
</style>
</head>
<body>
<header><div class="nav">
<a class="logo" href="{{ url_for('index') }}">🟢 NEXORA</a>
<div class="navlinks">
<a href="{{ url_for('index') }}">🏠 Главная</a>
<a href="{{ url_for('popular_page') }}">🔥 TOP</a><a href="{{ url_for('top_authors_page') }}">👑 Авторы</a>
{% if user %}<a href="{{ url_for('favorites_page') }}">⭐ Избранное</a><a href="{{ url_for('for_you_page') }}">🔥 Для тебя</a><a href="{{ url_for('achievements_page') }}">🏆 Награды</a><a href="{{ url_for('activity_page') }}">⚡ Лента</a><a href="{{ url_for('stats_page') }}">📊 Стата</a>{% endif %}
{% if user %}
<a href="{{ url_for('profile') }}">👤 {{ user['username'] }}</a>
<a href="{{ url_for('notifications') }}">🔔 {% if unread_count %}<b>{{ unread_count }}</b>{% else %}Уведомления{% endif %}</a><a href="{{ url_for('messages_page') }}">💬 {% if unread_messages %}<b>{{ unread_messages }}</b>{% else %}Чаты{% endif %}</a>
{% if user['role'] == 'admin' %}<a href="{{ url_for('admin') }}">⚙️ Админ</a>{% endif %}
<a href="{{ url_for('logout') }}">🚪 Выйти</a>
{% else %}
<a href="{{ url_for('login') }}">🔐 Войти</a><a href="{{ url_for('register') }}">📝 Регистрация</a>
{% endif %}
</div></div></header>
<div class="container">
{% with messages = get_flashed_messages() %}{% for message in messages %}<div class="flash">{{ message }}</div>{% endfor %}{% endwith %}
{{ body|safe }}
</div>
</body>
</html>
"""


def page(title, body):
    return render_template_string(
        BASE_HTML,
        title=title,
        body=body,
        user=current_user()
    )


# =========================================================
# ГЛАВНАЯ
# =========================================================

@app.route("/")
def index():

    search = request.args.get("search", "").strip()
    category = request.args.get("category", "").strip()

    conn = get_db()

    categories = conn.execute("""
        SELECT DISTINCT category
        FROM posts
        WHERE category IS NOT NULL
        AND category != ''
        ORDER BY category
    """).fetchall()

    query = "SELECT * FROM posts WHERE 1=1"
    params = []

    if search:
        query += " AND (title LIKE ? OR content LIKE ?)"
        params.extend([
            f"%{search}%",
            f"%{search}%"
        ])

    if category:
        query += " AND category = ?"
        params.append(category)

    query += " ORDER BY id DESC"

    posts = conn.execute(query, params).fetchall()

    conn.close()

    body = """
    <h1>🎬 Мой сайт</h1>

    <div class="card">

    <form class="search" method="get">

        <input
            type="text"
            name="search"
            placeholder="🔎 Найти пост..."
            value="{{ search }}"
        >

        <button>Найти</button>

    </form>

    </div>

    <div class="card">

    <form method="get">

        <label>Категория:</label>

        <select name="category" onchange="this.form.submit()">

            <option value="">Все категории</option>

            {% for c in categories %}

            <option
                value="{{ c['category'] }}"
                {% if category == c['category'] %}selected{% endif %}
            >
                {{ c['category'] }}
            </option>

            {% endfor %}

        </select>

    </form>

    </div>

    {% if posts %}

        {% for post in posts %}

        <div class="card post">

            {% if post['image'] %}
            <img src="{{ url_for('uploaded_file', filename=post['image']) }}">
            {% endif %}

            <h2>{{ post['title'] }}</h2>

            <div class="meta">
                📁 {{ post['category'] }}
                · 👁 {{ post['views'] }}
                · ❤️ {{ post['likes'] }}
                · {{ post['created_at'] }}
            </div>

            <p>
                {{ post['content'][:300] }}
                {% if post['content']|length > 300 %}...{% endif %}
            </p>

            <a class="btn" href="{{ url_for('view_post', post_id=post['id']) }}">
                Читать →
            </a>

        </div>

        {% endfor %}

    {% else %}

        <div class="card">
            <h3>Ничего не найдено 😢</h3>
        </div>

    {% endif %}
    """

    return render_template_string(
        BASE_HTML,
        title="Главная",
        body=render_template_string(
            body,
            posts=posts,
            categories=categories,
            search=search,
            category=category
        ),
        user=current_user()
    )


# =========================================================
# ПОСТ
# =========================================================

@app.route("/post/<int:post_id>")
def view_post(post_id):

    conn = get_db()

    post = conn.execute(
        "SELECT * FROM posts WHERE id = ?",
        (post_id,)
    ).fetchone()

    if not post:
        conn.close()
        return page(
            "Ошибка",
            "<div class='card'><h2>Пост не найден.</h2></div>"
        )

    conn.execute(
        "UPDATE posts SET views = views + 1 WHERE id = ?",
        (post_id,)
    )

    comments = conn.execute("""
        SELECT comments.*, users.username AS account_username
        FROM comments
        LEFT JOIN users ON users.id = comments.user_id
        WHERE comments.post_id = ?
        ORDER BY COALESCE(comments.parent_id, comments.id) DESC, comments.parent_id IS NOT NULL ASC, comments.id ASC
    """, (post_id,)).fetchall()

    conn.commit()
    conn.close()

    user = current_user()

    body = """
    <div class="card">

        {% if post['image'] %}
        <img
            src="{{ url_for('uploaded_file', filename=post['image']) }}"
            style="width:100%;max-height:500px;object-fit:cover;border-radius:12px;"
        >
        {% endif %}

        <h1>{{ post['title'] }}</h1>

        <div class="meta">
            📁 {{ post['category'] }}
            · 👁 {{ post['views'] + 1 }}
            · ❤️ {{ post['likes'] }}
        </div>

        <div class="content">{{ post['content'] }}</div>

        <div class="actions">

            {% if user %}
            <form method="post" action="{{ url_for('toggle_favorite', post_id=post['id']) }}">
                <button class="btn-gray">⭐ Избранное</button>
            </form>
            <form method="post" action="{{ url_for('rate_post', post_id=post['id']) }}" style="display:flex;gap:5px;align-items:center">
                <select name="rating" style="width:auto;margin:0">{% for n in range(1,6) %}<option value="{{ n }}">{{ n }} ⭐</option>{% endfor %}</select>
                <button>Оценить</button>
            </form>

            <form method="post" action="{{ url_for('like_post', post_id=post['id']) }}">
                <button>❤️ Лайк {{ post['likes'] }}</button>
            </form>
            {% else %}
            <a class="btn" href="{{ url_for('login') }}">
                ❤️ Войти, чтобы поставить лайк
            </a>
            {% endif %}

            {% if user and user['role'] == 'admin' %}

            <a class="btn" href="{{ url_for('edit_post', post_id=post['id']) }}">
                ✏️ Изменить
            </a>

            <form
                method="post"
                action="{{ url_for('delete_post', post_id=post['id']) }}"
                onsubmit="return confirm('Удалить пост?')"
            >
                <button class="btn-danger">🗑 Удалить</button>
            </form>

            {% endif %}

        </div>

    </div>

    <div class="card">

        <h2>💬 Комментарии</h2>

        {% if user %}

        <form method="post" action="{{ url_for('add_comment', post_id=post['id']) }}">

            <textarea
                name="text"
                placeholder="Напиши комментарий..."
                maxlength="1000"
                required
            ></textarea>

            <button>💬 Отправить</button>

        </form>

        {% else %}

        <p>Чтобы комментировать, нужно войти в аккаунт.</p>

        <a class="btn" href="{{ url_for('login') }}">
            🔐 Войти
        </a>

        {% endif %}

    </div>

    <div class="card">

        {% if comments %}

            {% for comment in comments %}

            <div class="comment">

                <div class="comment-user">
                    👤
                    {% if comment['account_username'] %}
                        {{ comment['account_username'] }}
                    {% else %}
                        {{ comment['username'] }}
                    {% endif %}
                </div>

                <div class="comment-date">
                    {{ comment['created_at'] }}
                </div>

                {% if comment['parent_id'] %}<div class="meta">↳ Ответ на комментарий</div>{% endif %}
                <p>{{ comment['text'] }}</p>

                {% if user %}
                <form method="post" action="{{ url_for('reply_comment', comment_id=comment['id']) }}" style="margin:8px 0 10px">
                    <input name="text" maxlength="1000" placeholder="Ответить..." required>
                    <button class="btn-gray">↩️ Ответить</button>
                </form>
                {% endif %}

                {% if user and user['role'] == 'admin' %}

                <form
                    method="post"
                    action="{{ url_for('delete_comment', comment_id=comment['id']) }}"
                >
                    <button class="btn-danger">🗑 Удалить</button>
                </form>

                {% endif %}

            </div>

            {% endfor %}

        {% else %}

            <p>Пока комментариев нет. Будь первым! 👇</p>

        {% endif %}

    </div>
    """

    return render_template_string(
        BASE_HTML,
        title=post["title"],
        body=render_template_string(
            body,
            post=post,
            comments=comments,
            user=user
        ),
        user=user
    )


# =========================================================
# ДОБАВИТЬ КОММЕНТАРИЙ
# =========================================================

@app.route("/comment/<int:post_id>", methods=["POST"])
@login_required
def add_comment(post_id):

    text = request.form.get("text", "").strip()
    user = current_user()

    if not text:
        flash("Комментарий пустой.")
        return redirect(url_for("view_post", post_id=post_id))

    if len(text) > 1000:
        flash("Комментарий слишком длинный.")
        return redirect(url_for("view_post", post_id=post_id))

    conn = get_db()

    post = conn.execute(
        "SELECT id FROM posts WHERE id = ?",
        (post_id,)
    ).fetchone()

    if not post:
        conn.close()
        flash("Пост не найден.")
        return redirect(url_for("index"))

    conn.execute("""
        INSERT INTO comments
        (post_id, username, text, user_id, created_at)
        VALUES (?, ?, ?, ?, ?)
    """, (
        post_id,
        user["username"],
        text,
        user["id"],
        datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ))

    author_row = conn.execute(
        "SELECT author_id FROM posts WHERE id = ?", (post_id,)
    ).fetchone()
    author_id = author_row["author_id"] if author_row else None

    conn.commit()
    conn.close()

    if author_id and author_id != user["id"]:
        add_notification(
            author_id,
            f"👤 {user['username']} оставил комментарий к твоему посту.",
            url_for("view_post", post_id=post_id)
        )

    check_achievements(user["id"])
    flash("Комментарий добавлен 👍")

    return redirect(url_for("view_post", post_id=post_id))


# =========================================================
# ЛАЙК
# =========================================================

@app.route("/like/<int:post_id>", methods=["POST"])
@login_required
def like_post(post_id):

    user = current_user()

    conn = get_db()

    already = conn.execute("""
        SELECT id
        FROM post_likes
        WHERE post_id = ?
        AND user_id = ?
    """, (post_id, user["id"])).fetchone()

    if already:
        flash("Ты уже поставил лайк ❤️")
    else:

        post = conn.execute(
            "SELECT id FROM posts WHERE id = ?",
            (post_id,)
        ).fetchone()

        if post:

            conn.execute("""
                INSERT INTO post_likes
                (post_id, user_id)
                VALUES (?, ?)
            """, (
                post_id,
                user["id"]
            ))

            conn.execute("""
                UPDATE posts
                SET likes = likes + 1
                WHERE id = ?
            """, (post_id,))

            conn.commit()

            flash("Лайк поставлен ❤️")

        else:
            flash("Пост не найден.")

    conn.close()

    return redirect(url_for("view_post", post_id=post_id))


# =========================================================
# РЕГИСТРАЦИЯ
# =========================================================

@app.route("/register", methods=["GET", "POST"])
def register():

    if session.get("user_id"):
        return redirect(url_for("index"))

    if request.method == "POST":

        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        password2 = request.form.get("password2", "")

        if not re.fullmatch(r"[A-Za-zА-Яа-яЁё0-9_]{3,20}", username):
            flash(
                "Логин: 3–20 символов, только буквы, цифры и _."
            )
            return redirect(url_for("register"))

        if len(password) < 6:
            flash("Пароль должен быть минимум 6 символов.")
            return redirect(url_for("register"))

        if password != password2:
            flash("Пароли не совпадают.")
            return redirect(url_for("register"))

        conn = get_db()

        exists = conn.execute(
            "SELECT id FROM users WHERE username = ?",
            (username,)
        ).fetchone()

        if exists:
            conn.close()
            flash("Такой пользователь уже существует.")
            return redirect(url_for("register"))

        password_hash = generate_password_hash(password)

        cursor = conn.execute("""
            INSERT INTO users
            (username, password, role, created_at)
            VALUES (?, ?, 'user', ?)
            RETURNING id
        """, (
            username,
            password_hash,
            datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ))

        user_id = cursor.fetchone()["id"]
        conn.commit()

        conn.close()

        session["user_id"] = user_id

        flash("Аккаунт создан! Добро пожаловать 🎉")

        return redirect(url_for("profile"))

    body = """
    <div class="card">

        <h1>📝 Регистрация</h1>

        <form method="post">

            <label>Логин</label>

            <input
                name="username"
                placeholder="Например: Muhammad"
                maxlength="20"
                required
            >

            <label>Пароль</label>

            <input
                type="password"
                name="password"
                placeholder="Минимум 6 символов"
                required
            >

            <label>Повтори пароль</label>

            <input
                type="password"
                name="password2"
                required
            >

            <button>Создать аккаунт 🚀</button>

        </form>

    </div>
    """

    return page(
        "Регистрация",
        render_template_string(body)
    )


# =========================================================
# ВХОД
# =========================================================

@app.route("/login", methods=["GET", "POST"])
def login():

    if session.get("user_id"):
        return redirect(url_for("index"))

    if request.method == "POST":

        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")

        conn = get_db()

        user = conn.execute(
            "SELECT * FROM users WHERE username = ?",
            (username,)
        ).fetchone()

        if not user:

            conn.close()

            flash("Неверный логин или пароль.")
            return redirect(url_for("login"))

        password_ok = False

        # Новый безопасный пароль Werkzeug
        try:
            password_ok = check_password_hash(
                user["password"],
                password
            )
        except Exception:
            password_ok = False

        # Совместимость со старым SHA-256
        if not password_ok and len(user["password"]) == 64:

            old_hash = hashlib.sha256(
                password.encode()
            ).hexdigest()

            if secrets.compare_digest(
                old_hash,
                user["password"]
            ):
                password_ok = True

                # Автоматически переводим на новый хеш
                new_hash = generate_password_hash(password)

                conn.execute("""
                    UPDATE users
                    SET password = ?
                    WHERE id = ?
                """, (
                    new_hash,
                    user["id"]
                ))

                conn.commit()

        if not password_ok:

            conn.close()

            flash("Неверный логин или пароль.")
            return redirect(url_for("login"))

        session.clear()
        session["user_id"] = user["id"]

        conn.close()

        flash("Вы вошли в аккаунт 👋")

        return redirect(url_for("index"))

    body = """
    <div class="card">

        <h1>🔐 Вход</h1>

        <form method="post">

            <label>Логин</label>

            <input
                name="username"
                required
            >

            <label>Пароль</label>

            <input
                type="password"
                name="password"
                required
            >

            <button>Войти</button>

        </form>

        <br>

        <a class="btn btn-gray" href="{{ url_for('register') }}">
            Нет аккаунта? Регистрация
        </a>

    </div>
    """

    return page(
        "Вход",
        render_template_string(body)
    )


# =========================================================
# ВЫХОД
# =========================================================

@app.route("/logout")
def logout():

    session.clear()

    flash("Вы вышли из аккаунта.")

    return redirect(url_for("index"))


# =========================================================
# ПРОФИЛЬ
# =========================================================

@app.route("/profile")
@login_required
def profile():

    user = current_user()

    conn = get_db()

    comments_count = conn.execute("""
        SELECT COUNT(*)
        FROM comments
        WHERE user_id = ?
    """, (user["id"],)).fetchone()[0]

    likes_count = conn.execute("""
        SELECT COUNT(*)
        FROM post_likes
        WHERE user_id = ?
    """, (user["id"],)).fetchone()[0]

    recent_comments = conn.execute("""
        SELECT comments.*, posts.title
        FROM comments
        LEFT JOIN posts ON posts.id = comments.post_id
        WHERE comments.user_id = ?
        ORDER BY comments.id DESC
        LIMIT 10
    """, (user["id"],)).fetchall()

    conn.close()

    first_letter = user["username"][0].upper()

    body = """
    <div class="card">

        {% if user['avatar'] %}
        <img src="{{ url_for('uploaded_file', filename=user['avatar']) }}"
             style="width:90px;height:90px;object-fit:cover;border-radius:50%;margin-bottom:15px;">
        {% else %}
        <div class="profile-avatar">
            {{ first_letter }}
        </div>
        {% endif %}

        <h1>👤 {{ user['username'] }}</h1>

        <div class="meta">
            Аккаунт создан: {{ user['created_at'] }}
        </div>

        {% if user['role'] == 'admin' %}
        <p>🛡️ Администратор</p>
        {% else %}
        <p>👤 Пользователь</p>
        {% endif %}

        <div>

            <div class="stat">
                💬 Комментариев: {{ comments_count }}
            </div>

            <div class="stat">
                ❤️ Лайков: {{ likes_count }}
            </div>

        </div>

        <div class="actions">
            <a class="btn" href="{{ url_for('edit_profile') }}">✏️ Редактировать профиль</a>
            <a class="btn btn-gray" href="{{ url_for('change_password') }}">🔑 Сменить пароль</a>
        </div>

    </div>

    <div class="card">

        <h2>💬 Мои комментарии</h2>

        {% if recent_comments %}

            {% for comment in recent_comments %}

            <div class="comment">

                <b>{{ comment['title'] or 'Удалённый пост' }}</b>

                <div class="comment-date">
                    {{ comment['created_at'] }}
                </div>

                <p>{{ comment['text'] }}</p>

            </div>

            {% endfor %}

        {% else %}

            <p>Ты пока ничего не комментировал.</p>

        {% endif %}

    </div>
    """

    return render_template_string(
        BASE_HTML,
        title="Профиль",
        body=render_template_string(
            body,
            user=user,
            first_letter=first_letter,
            comments_count=comments_count,
            likes_count=likes_count,
            recent_comments=recent_comments
        ),
        user=user
    )


# =========================================================
# АДМИНКА
# =========================================================

@app.route("/admin")
@admin_required
def admin():

    conn = get_db()

    posts = conn.execute(
        "SELECT * FROM posts ORDER BY id DESC"
    ).fetchall()

    users = conn.execute("""
        SELECT
            users.*,
            (
                SELECT COUNT(*)
                FROM comments
                WHERE comments.user_id = users.id
            ) AS comment_count
        FROM users
        ORDER BY users.id DESC
    """).fetchall()

    comments = conn.execute("""
        SELECT comments.*, posts.title
        FROM comments
        LEFT JOIN posts ON posts.id = comments.post_id
        ORDER BY comments.id DESC
        LIMIT 30
    """).fetchall()

    conn.close()

    body = """
    <h1>⚙️ Панель администратора</h1>

    <div class="card">

        <h2>➕ Добавить пост</h2>

        <a class="btn btn-green" href="{{ url_for('add_post') }}">
            Создать пост
        </a>

        <a class="btn btn-gray" href="{{ url_for('backup') }}">
            💾 Скачать backup
        </a>

    </div>

    <div class="card">

        <h2>📚 Посты</h2>

        {% for post in posts %}

        <div class="comment">

            <b>{{ post['title'] }}</b>

            <div class="meta">
                📁 {{ post['category'] }}
                · 👁 {{ post['views'] }}
                · ❤️ {{ post['likes'] }}
            </div>

            <div class="actions">

                <a class="btn" href="{{ url_for('view_post', post_id=post['id']) }}">
                    👁 Открыть
                </a>

                <a class="btn" href="{{ url_for('edit_post', post_id=post['id']) }}">
                    ✏️ Изменить
                </a>

                <form
                    method="post"
                    action="{{ url_for('delete_post', post_id=post['id']) }}"
                    onsubmit="return confirm('Удалить пост?')"
                >
                    <button class="btn-danger">🗑 Удалить</button>
                </form>

            </div>

        </div>

        {% endfor %}

    </div>

    <div class="card">

        <h2>👥 Пользователи</h2>

        {% for u in users %}

        <div class="comment">

            👤 <b>{{ u['username'] }}</b>

            {% if u['role'] == 'admin' %}
            🛡️ ADMIN
            {% endif %}

            <div class="meta">
                💬 {{ u['comment_count'] }}
                · {{ u['created_at'] }}
            </div>

        </div>

        {% endfor %}

    </div>

    <div class="card">

        <h2>💬 Последние комментарии</h2>

        {% for comment in comments %}

        <div class="comment">

            <b>{{ comment['username'] }}</b>

            · {{ comment['title'] or 'Удалённый пост' }}

            <p>{{ comment['text'] }}</p>

            <form
                method="post"
                action="{{ url_for('delete_comment', comment_id=comment['id']) }}"
            >
                <button class="btn-danger">🗑 Удалить</button>
            </form>

        </div>

        {% else %}

        <p>Комментариев нет.</p>

        {% endfor %}

    </div>
    """

    return render_template_string(
        BASE_HTML,
        title="Админка",
        body=render_template_string(
            body,
            posts=posts,
            users=users,
            comments=comments
        ),
        user=current_user()
    )


# =========================================================
# ДОБАВЛЕНИЕ ПОСТА
# =========================================================

@app.route("/add", methods=["GET", "POST"])
@admin_required
def add_post():

    if request.method == "POST":

        title = request.form.get("title", "").strip()
        content = request.form.get("content", "").strip()
        category = request.form.get(
            "category",
            "Без категории"
        ).strip()

        image_name = None

        image = request.files.get("image")

        if image and image.filename:

            if not allowed_file(image.filename):
                flash("Можно загружать только JPG, JPEG, PNG, GIF или WEBP.")
                return redirect(url_for("add_post"))

            filename = secure_filename(image.filename)

            # Уникальное имя
            ext = filename.rsplit(".", 1)[1].lower()

            filename = (
                secrets.token_hex(8)
                + "."
                + ext
            )

            image.save(
                os.path.join(
                    app.config["UPLOAD_FOLDER"],
                    filename
                )
            )

            image_name = filename

        if not title or not content:

            flash("Заполни заголовок и текст.")

            return redirect(url_for("add_post"))

        conn = get_db()

        admin_user = current_user()

        conn.execute("""
            INSERT INTO posts
            (title, content, category, image, likes, views, created_at, author_id)
            VALUES (?, ?, ?, ?, 0, 0, ?, ?)
        """, (
            title,
            content,
            category or "Без категории",
            image_name,
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            admin_user["id"] if admin_user else None
        ))

        conn.commit()
        conn.close()

        flash("Пост создан 🎉")

        return redirect(url_for("admin"))

    body = """
    <div class="card">

        <h1>➕ Новый пост</h1>

        <form method="post" enctype="multipart/form-data">

            <label>Название</label>

            <input
                name="title"
                placeholder="Название поста"
                required
            >

            <label>Категория</label>

            <input
                name="category"
                placeholder="Аниме, фильмы, новости..."
            >

            <label>Текст</label>

            <textarea
                name="content"
                placeholder="Текст поста..."
                required
            ></textarea>

            <label>Картинка</label>

            <input
                type="file"
                name="image"
                accept=".jpg,.jpeg,.png,.gif,.webp"
            >

            <button>🚀 Опубликовать</button>

        </form>

    </div>
    """

    return page(
        "Новый пост",
        render_template_string(body)
    )


# =========================================================
# РЕДАКТИРОВАНИЕ ПОСТА
# =========================================================

@app.route("/edit/<int:post_id>", methods=["GET", "POST"])
@admin_required
def edit_post(post_id):

    conn = get_db()

    post = conn.execute(
        "SELECT * FROM posts WHERE id = ?",
        (post_id,)
    ).fetchone()

    if not post:

        conn.close()

        flash("Пост не найден.")

        return redirect(url_for("admin"))

    if request.method == "POST":

        title = request.form.get("title", "").strip()
        content = request.form.get("content", "").strip()
        category = request.form.get(
            "category",
            "Без категории"
        ).strip()

        image_name = post["image"]

        image = request.files.get("image")

        if image and image.filename:

            if not allowed_file(image.filename):

                conn.close()

                flash("Неподдерживаемый формат картинки.")

                return redirect(
                    url_for("edit_post", post_id=post_id)
                )

            filename = secure_filename(image.filename)

            ext = filename.rsplit(".", 1)[1].lower()

            filename = secrets.token_hex(8) + "." + ext

            image.save(
                os.path.join(
                    app.config["UPLOAD_FOLDER"],
                    filename
                )
            )

            image_name = filename

        conn.execute("""
            UPDATE posts
            SET title = ?,
                content = ?,
                category = ?,
                image = ?
            WHERE id = ?
        """, (
            title,
            content,
            category or "Без категории",
            image_name,
            post_id
        ))

        conn.commit()
        conn.close()

        flash("Пост обновлён ✏️")

        return redirect(url_for("view_post", post_id=post_id))

    conn.close()

    body = """
    <div class="card">

        <h1>✏️ Редактирование</h1>

        <form method="post" enctype="multipart/form-data">

            <label>Название</label>

            <input
                name="title"
                value="{{ post['title'] }}"
                required
            >

            <label>Категория</label>

            <input
                name="category"
                value="{{ post['category'] }}"
            >

            <label>Текст</label>

            <textarea name="content" required>{{ post['content'] }}</textarea>

            <label>Новая картинка</label>

            <input
                type="file"
                name="image"
                accept=".jpg,.jpeg,.png,.gif,.webp"
            >

            <button>💾 Сохранить</button>

        </form>

    </div>
    """

    return page(
        "Редактирование",
        render_template_string(body, post=post)
    )


# =========================================================
# УДАЛЕНИЕ ПОСТА
# =========================================================

@app.route("/delete/<int:post_id>", methods=["POST"])
@admin_required
def delete_post(post_id):

    conn = get_db()

    post = conn.execute(
        "SELECT * FROM posts WHERE id = ?",
        (post_id,)
    ).fetchone()

    if post:

        if post["image"]:

            image_path = os.path.join(
                app.config["UPLOAD_FOLDER"],
                post["image"]
            )

            if os.path.exists(image_path):

                try:
                    os.remove(image_path)
                except Exception:
                    pass

        conn.execute(
            "DELETE FROM posts WHERE id = ?",
            (post_id,)
        )

        conn.commit()

        flash("Пост удалён.")

    conn.close()

    return redirect(url_for("admin"))


# =========================================================
# УДАЛЕНИЕ КОММЕНТАРИЯ
# =========================================================

@app.route("/delete_comment/<int:comment_id>", methods=["POST"])
@admin_required
def delete_comment(comment_id):

    conn = get_db()

    conn.execute(
        "DELETE FROM comments WHERE id = ?",
        (comment_id,)
    )

    conn.commit()
    conn.close()

    flash("Комментарий удалён.")

    return redirect(request.referrer or url_for("admin"))


# =========================================================
# РЕДАКТИРОВАНИЕ ПРОФИЛЯ
# =========================================================

@app.route("/profile/edit", methods=["GET", "POST"])
@login_required
def edit_profile():
    user = current_user()

    if request.method == "POST":
        new_username = request.form.get("username", "").strip()
        avatar = request.files.get("avatar")

        if not re.fullmatch(r"[A-Za-zА-Яа-яЁё0-9_]{3,20}", new_username):
            flash("Логин: 3–20 символов, только буквы, цифры и _.")
            return redirect(url_for("edit_profile"))

        conn = get_db()

        exists = conn.execute(
            "SELECT id FROM users WHERE username = ? AND id != ?",
            (new_username, user["id"])
        ).fetchone()

        if exists:
            conn.close()
            flash("Этот логин уже занят.")
            return redirect(url_for("edit_profile"))

        avatar_name = user["avatar"]

        if avatar and avatar.filename:
            if not allowed_file(avatar.filename):
                conn.close()
                flash("Аватар: JPG, JPEG, PNG, GIF или WEBP.")
                return redirect(url_for("edit_profile"))

            ext = avatar.filename.rsplit(".", 1)[1].lower()
            avatar_name = "avatar_" + secrets.token_hex(10) + "." + ext
            avatar.save(os.path.join(app.config["UPLOAD_FOLDER"], avatar_name))

        conn.execute(
            "UPDATE users SET username = ?, avatar = ? WHERE id = ?",
            (new_username, avatar_name, user["id"])
        )
        conn.commit()
        conn.close()

        flash("Профиль обновлён ✨")
        return redirect(url_for("profile"))

    body = """
    <div class="card">
        <h1>✏️ Редактирование профиля</h1>

        <form method="post" enctype="multipart/form-data">
            <label>Логин</label>
            <input name="username" value="{{ user['username'] }}" maxlength="20" required>

            <label>Аватар</label>
            <input type="file" name="avatar" accept=".jpg,.jpeg,.png,.gif,.webp">

            <button>💾 Сохранить</button>
        </form>
    </div>
    """

    return page("Редактирование профиля",
                render_template_string(body, user=user))


# =========================================================
# СМЕНА ПАРОЛЯ
# =========================================================

@app.route("/profile/password", methods=["GET", "POST"])
@login_required
def change_password():
    user = current_user()

    if request.method == "POST":
        old_password = request.form.get("old_password", "")
        new_password = request.form.get("new_password", "")
        new_password2 = request.form.get("new_password2", "")

        ok = False

        try:
            ok = check_password_hash(user["password"], old_password)
        except Exception:
            ok = False

        if not ok and len(user["password"]) == 64:
            old_hash = hashlib.sha256(old_password.encode()).hexdigest()
            ok = secrets.compare_digest(old_hash, user["password"])

        if not ok:
            flash("Старый пароль неверный.")
            return redirect(url_for("change_password"))

        if len(new_password) < 6:
            flash("Новый пароль должен быть минимум 6 символов.")
            return redirect(url_for("change_password"))

        if new_password != new_password2:
            flash("Новые пароли не совпадают.")
            return redirect(url_for("change_password"))

        conn = get_db()
        conn.execute(
            "UPDATE users SET password = ? WHERE id = ?",
            (generate_password_hash(new_password), user["id"])
        )
        conn.commit()
        conn.close()

        flash("Пароль успешно изменён 🔐")
        return redirect(url_for("profile"))

    body = """
    <div class="card">
        <h1>🔑 Смена пароля</h1>

        <form method="post">
            <label>Старый пароль</label>
            <input type="password" name="old_password" required>

            <label>Новый пароль</label>
            <input type="password" name="new_password" minlength="6" required>

            <label>Повтори новый пароль</label>
            <input type="password" name="new_password2" minlength="6" required>

            <button>🔐 Изменить пароль</button>
        </form>
    </div>
    """

    return page("Смена пароля",
                render_template_string(body, user=user))


# =========================================================
# УВЕДОМЛЕНИЯ
# =========================================================

@app.route("/notifications")
@login_required
def notifications():
    user = current_user()

    conn = get_db()
    items = conn.execute("""
        SELECT *
        FROM notifications
        WHERE user_id = ?
        ORDER BY id DESC
        LIMIT 50
    """, (user["id"],)).fetchall()

    conn.execute(
        "UPDATE notifications SET is_read = 1 WHERE user_id = ?",
        (user["id"],)
    )
    conn.commit()
    conn.close()

    body = """
    <div class="card">
        <h1>🔔 Уведомления</h1>

        {% if items %}
            {% for n in items %}
            <div class="comment">
                <div>{{ n['text'] }}</div>
                <div class="comment-date">{{ n['created_at'] }}</div>

                {% if n['link'] %}
                <div class="actions">
                    <a class="btn btn-gray" href="{{ n['link'] }}">Открыть →</a>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        {% else %}
            <p>Уведомлений пока нет 😊</p>
        {% endif %}
    </div>
    """

    return page("Уведомления",
                render_template_string(body, items=items))


# =========================================================
# UPLOADS
# =========================================================


@app.route("/uploads/<path:filename>")
def uploaded_file(filename):

    return send_from_directory(
        app.config["UPLOAD_FOLDER"],
        filename
    )


# =========================================================
# BACKUP
# =========================================================

@app.route("/admin/backup")
@admin_required
def backup():
    if os.environ.get("DATABASE_URL"):
        return page("Backup", "<div class='card'><h2>💾 Backup PostgreSQL</h2><p>Для облачной базы используйте резервные копии PostgreSQL/Render. Локальный site.db больше не является основной базой.</p></div>")
    return send_from_directory(
        BASE_DIR,
        "site.db",
        as_attachment=True,
        download_name="site_backup.db"
    )


# =========================================================
# ERROR 413
# =========================================================

@app.errorhandler(413)
def too_large(error):

    flash("Картинка слишком большая. Максимум 5 МБ.")

    return redirect(request.referrer or url_for("index"))


# =========================================================
# ЗАПУСК
# =========================================================

if __name__ == "__main__":

    print()
    print("=" * 50)
    print("🚀 NEXORA 11.0 ЗАПУЩЕН — PostgreSQL ready")
    print("=" * 50)
    print("📱 Открой:")
    print("http://127.0.0.1:5000")
    print()
    print("👑 Администратор:")
    print("Логин: admin")
    print("Пароль: 1234")
    print("=" * 50)
    print()

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=False
    )